[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "stock-crawl"
version = "0.1.6"
authors = [
  { name="Seria Ati", email="seria.ati@gmail.com" },
]
description = "Python package for crawling stock data"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GPL-3.0 License",
    "Operating System :: OS Independent",
]
dependencies = [
  "aiohttp>=3.8.5",
  "beautifulsoup4>=4.12.2",
  "lxml>=4.9.3",
  "tortoise-orm>=0.20.0",
  "pydantic>=2.0.0",
  "fake-useragent>=1.3.0",
  "cachetools>=5.3.1",
  "asyncache>=0.3.1",
]