line-length = 100
target-version = "py312"

[lint]
preview = true
select = [
    "F",
    "E",
    "W",
    "C90",
    "I",
    "N",
    "UP",
    "ANN",
    "ASYNC",
    "S",
    "FBT",
    "B",
    "A",
    "C4",
    "DTZ",
    "EM",
    "FA",
    "ISC",
    "LOG",
    "G",
    "PIE",
    "T20",
    "PT",
    "RSE",
    "RET",
    "SLOT",
    "SIM",
    "TC",
    "ARG",
    "PTH",
    "PL",
    "TRY",
    "FAST",
    "PERF",
    "FURB",
    "RUF",
]
ignore = [
    "S101",    # Assert used
    "PLR2004", # Magic value used
    "RUF003",  # Comment contains ambiguous character
    "PLR6301", # Method could be a function, class method, or static method
    "ANN401",  # typing.Any used
    "DTZ007",  # Naive datetime constructed
]

[lint.per-file-ignores]
"**/__init__.py" = ["F403", "F401"] # Wildcard imports used
